install(FILES io.github.martikan.ChessTrainer.desktop
        DESTINATION ${KDE_INSTALL_APPDIR})

install(FILES io.github.martikan.ChessTrainer.metainfo.xml
        DESTINATION ${KDE_INSTALL_METAINFODIR})

install(FILES icons/io.github.martikan.ChessTrainer.svg
        DESTINATION ${KDE_INSTALL_ICONDIR}/hicolor/scalable/apps)
